version: 2
jobs:
  build:
    
    working_directory: ~/spring-boot-rest-api-example

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: spring-boot-rest-api-example-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-rest-api-example-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/dialogs-0.0.1-SNAPSHOT.jar

